apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: novashop-cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: certificate-management
    app.kubernetes.io/part-of: novashop
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: novashop-platform
  sources:
    - repoURL: quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: v1.21.0
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/kubernetes/cert-manager/helm-values.yaml
    - repoURL: https://github.com/nguyenlpn2015/NovaShop.git
      targetRevision: c2a3db20bfbfc8d7aa790a751842158359f3f155
      ref: values
    - repoURL: https://github.com/nguyenlpn2015/NovaShop.git
      targetRevision: c2a3db20bfbfc8d7aa790a751842158359f3f155
      path: kubernetes/cert-manager
      directory:
        recurse: false
        include: "{namespace.yaml,clusterissuer.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
