apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: novashop-redis-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: novashop
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: novashop-platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-redis-exporter
      targetRevision: 6.28.0
      helm:
        releaseName: novashop-redis-exporter
        valueFiles:
          - $values/kubernetes/observability/redis-exporter/helm-values.yaml
    - repoURL: https://github.com/nguyenlpn2015/NovaShop.git
      targetRevision: e4c901f3948d2e156e1b21b55b310684932724a0
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
