apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: novashop
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "0"
      - op: replace
        path: /spec/template/spec/sources/0/helm/valueFiles
        value:
          - "$values/apps/novashop/values/{{ .valuesFile }}"
          - "$values/apps/novashop/targets/ubuntu-k3s/{{ .valuesFile }}"
      - op: add
        path: /spec/template/spec/sources/-
        value:
          repoURL: https://github.com/nguyenlpn2015/NovaShop.git
          targetRevision: b9405fe14a0b2e619b791e15cfb3d668366d07eb
          path: kubernetes/ingress/http
          directory:
            recurse: false
            include: "{{ .valuesFile }}"
