namespace:
  create: false
  name: novashop-production

config:
  environment: production
  nextPublicApiUrl: https://api.novashop.example.com

secrets:
  existingSecret: novashop-production-secrets

backend:
  replicaCount: 3
  image:
    tag: "68a27fc8d21ea19cde615a34cf20687d98c3ac9b"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

frontend:
  replicaCount: 3
  image:
    tag: "68a27fc8d21ea19cde615a34cf20687d98c3ac9b"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

ingress:
  frontendHost: novashop.example.com
  backendHost: api.novashop.example.com
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    enabled: true
    secretName: novashop-production-tls
