namespace:
  create: false
  name: novashop-staging

config:
  environment: staging
  nextPublicApiUrl: https://api.staging.novashop.example.com

secrets:
  existingSecret: novashop-staging-secrets

backend:
  replicaCount: 2
  image:
    tag: "633c2c41164dec89284b29706cf8c4d0f02de0cb"

frontend:
  replicaCount: 2
  image:
    tag: "633c2c41164dec89284b29706cf8c4d0f02de0cb"

ingress:
  frontendHost: staging.novashop.example.com
  backendHost: api.staging.novashop.example.com
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    enabled: true
    secretName: novashop-staging-tls
