namespace:
  create: false
  name: novashop-staging

config:
  environment: staging
  nextPublicApiUrl: https://api.staging.novashop.example.com

secrets:
  existingSecret: novashop-staging-secrets

backend:
  replicaCount: 2
  image:
    tag: "68a27fc8d21ea19cde615a34cf20687d98c3ac9b"

frontend:
  replicaCount: 2
  image:
    tag: "68a27fc8d21ea19cde615a34cf20687d98c3ac9b"

ingress:
  frontendHost: staging.novashop.example.com
  backendHost: api.staging.novashop.example.com
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    enabled: true
    secretName: novashop-staging-tls
